version: '3.4'
services:
  cli: &cli
    depends_on:
      - testdb
    image: php:7.2-alpine
    volumes:
      - .:/project:rw
    environment:
      COLORS: 1
    entrypoint: ["/project/entrypoint.sh"]
    command: "bug"
  testdb:
    image: mariadb
    tmpfs:
      - /var/lib/mysql
    command: --character-set-server=utf8
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
    healthcheck:
      test: lsof -i :3306

  cli73:
    <<: *cli
    image: php:7.3-rc-alpine
  cli72:
    <<: *cli
  cli71:
    <<: *cli
    image: php:7.1-alpine
  cli70:
    <<: *cli
    image: php:7.0-alpine